import type { Metadata } from "next";
import "./globals.css";
import 'animate.css';
import { Toaster } from "react-hot-toast";

import { Inter } from 'next/font/google';
import { Providers } from "./provider";
const inter = Inter({ 
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>{children}</Providers>
                <Toaster position="top-right" reverseOrder={false} />

      </body>
    </html>
  );
}